import {act,addDemoPartner,clearSession,createRoom,getSession,handOver,joinRoom,loadRoom,saveSession,storageMode} from "./storage.js";
import {migrateState} from "./game.js";
const view={state:null,session:null,mode:"home",selected:null,busy:false,error:""};
const esc=(v="")=>String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const art={
 customer:`<svg viewBox="0 0 520 330"><path d="M55 290q85-9 181-2t230-1M92 281q4-82 41-105 28-18 68 2 32 17 41 103M134 174q-17-39 4-74 30-45 72-9 16 13 13 42-3 30-25 46M133 109q36-31 87 0M156 127h3m27 0h3M165 145q10 8 22 0M100 204l-38 53m159-51 48 38M253 286q5-95 48-123 42-28 92 9 36 28 45 114M309 162q-10-38 21-61 35-25 68 7 21 21 10 61M324 112q40 18 82 4M346 137h3m25 0h3M352 152q12 7 24-1M300 215l-51 32m143-39 46 37"/><path d="M216 267h125M237 267v-70h84v70M249 220h60m-46-23v70m30-70v70M151 248q37-20 76 0M160 247v29h61v-29"/></svg>`,
 store:`<svg viewBox="0 0 620 430"><path d="M32 376q64-9 119-3t116 1q74-8 142 0t175-2M74 363V165l60-59 352 9 62 54v195M70 166q72 10 145-2t146 2q94 10 190 0M100 145V92h410v64M115 119h380M105 198h250v135H105zM122 226h215M122 272h215M165 198v135M245 198v135M383 190h122v174H383zM400 213h87v103h-87zM435 316v47M147 221l13-13 12 13m54 0 12-13 13 13m-104 48 15-12 14 12m52 0 14-12 15 12M280 363q0-69 39-69t42 69M299 305q20-24 42 0M307 326l-20 22m53-22 21 22"/></svg>`,
 map:`<svg viewBox="0 0 230 190"><path d="M24 42q22-22 48-11l10 25 26 1 12-25 33-8 28 16 20 42-11 40-38 6-22 31-38-12-31 12-18-35-20-39zM40 78l42 28 40-19 44 24m-84-5 10 41m30-60 30-36"/><circle cx="40" cy="78" r="3"/><circle cx="82" cy="106" r="3"/><circle cx="122" cy="87" r="3"/><circle cx="166" cy="111" r="3"/></svg>`
};
function landing(){return `<main class="storybook home"><header><b>中超合伙人</b><span>双人倒时差经营冒险</span></header><section class="home-grid"><div><small>从一间小店，到整个欧洲</small><h1>欧洲<br>中超之王</h1><p>你管白天，朋友守夜班。从伦敦的一家小店开始，把中国味道带到欧洲每一条街。</p><button class="ink-btn" data-mode="create">开始创业 →</button><button class="ink-link" data-mode="join">凭房间码加入合伙</button><i>${storageMode==="cloud"?"云端营业中":"本地试玩模式"}</i></div><div class="home-art">${art.store}<em>一家在异国他乡亮着灯的小店</em></div></section>${view.mode==="home"?"":entry()}</main>`;}
function entry(){const j=view.mode==="join";return `<div class="paper-modal"><section><button class="x" data-mode="home">×</button><small>${j?"JOIN BUSINESS":"NEW BUSINESS"}</small><h2>${j?"找到朋友的店":"给第一家店开门"}</h2><label>合伙人名字<input id="name" maxlength="12" placeholder="例如：小林"></label>${j?'<label>六位房间码<input id="code" maxlength="6" placeholder="LONDON"></label>':""}${view.error?`<p>${esc(view.error)}</p>`:""}<button class="ink-btn" id="enter">${j?"加入合伙":"租下这家店"}</button></section></div>`;}
function game(){const s=migrateState(view.state);view.state=s;const partner=s.players.find(p=>p.id!==view.session.playerId),mine=s.currentPlayer===view.session.playerId;return `<main class="storybook game"><header><h1>${s.storeName}</h1><span>${s.city}　·　第 ${s.day} 天　·　房间码 ${s.code} <button id="copy">复制</button> <button id="leave">退出</button></span></header>${mine?turn(s,partner):waiting(partner)}</main>`;}
function turn(s,partner){const e=s.event,chosen=e.choices.find(c=>c.id===view.selected);return `<section class="story-grid"><aside class="shift-side"><div class="draw-clock"><i></i><b>${s.shiftHours}</b><span>小时</span></div><h3>本班还剩 ${s.shiftHours} 小时</h3><p>已接待 ${s.customersThisShift} 位顾客</p><button class="next-label">下一位顾客 →</button><div class="choice-list"><h2>你具体做了什么？</h2>${e.choices.map((c,i)=>`<button data-item="${c.id}" class="${view.selected===c.id?"on":""}"><i>${i+1}</i><span><b>${c.label}</b><small>${c.detail}</small></span></button>`).join("")}</div></aside><article class="encounter"><p class="event-tag">${e.type==="sale"?"柜台来客":"街区来事"} · ${e.goal}</p><div class="people-drawing">${art.customer}<div><small>${e.title}</small><h2>${e.who}</h2><p>“${e.text}”</p></div></div><div class="write-action"><label>记录一下（自由填写）</label><textarea id="action" maxlength="120" placeholder="例如：给泡面放最辣的辣椒酱，让他直接醒一晚上熬夜肝论文"></textarea><small id="action-count">0/120</small></div>${chosen?`<p class="picked">基础方案：${chosen.label}</p>`:""}<div class="finish"><input id="note" maxlength="30" placeholder="给合伙人留一句话（可选）"><button id="serve" ${!chosen?"disabled":""}>继续营业</button><button id="early-handoff">提前交班</button></div>${view.error?`<p>${esc(view.error)}</p>`:""}</article><aside class="world-side"><div class="money-note"><b>现金：£${s.cash}</b><span>口碑：${s.fame} / 风险：${s.risk}</span></div><div class="partner-note"><h3>伙伴小记：</h3><p>${esc(s.note||"今天的货卖得不错，记得看看街区里有没有新动静。")}</p></div><div class="world-map"><h3>欧洲路线图</h3>${art.map}<p>${esc(s.worldNews)}</p></div></aside></section>`;}
function waiting(p){return `<section class="waiting"><div>${art.customer}</div><h2>店铺在另一个时区继续营业</h2><p>${p?`现在轮到 ${esc(p.name)} 值班。把这一页留给对方。`:"把房间码发给你的合伙人。"}</p><button class="ink-btn" id="refresh">看看新的合伙笔记</button>${storageMode==="local"&&p?'<button class="ink-link" id="switch-demo">切换为另一位合伙人</button>':""}</section>`;}
function render(){document.querySelector("#app").innerHTML=view.state&&view.session?game():landing();bind();}
function bind(){document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{view.mode=b.dataset.mode;view.error="";render()});document.querySelector("#enter")?.addEventListener("click",enter);document.querySelectorAll("[data-item]").forEach(b=>b.onclick=()=>{view.selected=b.dataset.item;render()});document.querySelector("#action")?.addEventListener("input",e=>document.querySelector("#action-count").textContent=`${e.target.value.length}/120`);document.querySelector("#serve")?.addEventListener("click",serve);document.querySelector("#early-handoff")?.addEventListener("click",earlyHandoff);document.querySelector("#refresh")?.addEventListener("click",refresh);document.querySelector("#switch-demo")?.addEventListener("click",switchDemo);document.querySelector("#copy")?.addEventListener("click",()=>navigator.clipboard?.writeText(view.state.code));document.querySelector("#leave")?.addEventListener("click",()=>{clearSession();Object.assign(view,{state:null,session:null,selected:null});render()});}
async function enter(){const n=document.querySelector("#name").value.trim(),c=document.querySelector("#code")?.value.trim().toUpperCase();if(!n||(view.mode==="join"&&c.length!==6)){view.error="请填好名字和房间码";return render()}view.busy=true;try{const r=view.mode==="create"?await createRoom(n):await joinRoom(c,n);view.state=r.state;view.session=r.session;view.selected=null;saveSession(r.session)}catch(e){view.error=e.message}view.busy=false;render();}
async function serve(){const a=document.querySelector("#action")?.value||"",n=document.querySelector("#note")?.value||"";view.busy=true;try{if(view.state.players.length<2)view.state=await addDemoPartner(view.session);view.state=await act(view.session,view.selected,a,n,false);view.selected=null;view.error=""}catch(e){view.error=e.message}view.busy=false;render();}
async function earlyHandoff(){if(view.state.players.length<2)view.state=await addDemoPartner(view.session);try{view.state=await handOver(view.session,document.querySelector("#note")?.value||"提前交班");view.selected=null}catch(e){view.error=e.message}render();}
async function refresh(){try{view.state=await loadRoom(view.session)}catch(e){view.error=e.message}render();}
async function switchDemo(){const o=view.state.players.find(p=>p.id!==view.session.playerId);if(!o)return;view.session={code:view.state.code,token:o.token,playerId:o.id};saveSession(view.session);render();}
export async function mountApp(){view.session=getSession();if(view.session){try{view.state=await loadRoom(view.session)}catch{clearSession();view.session=null}}render();setInterval(async()=>{if(view.session&&view.state?.currentPlayer!==view.session.playerId)await refresh()},10000);}
